#!/usr/bin/env python3
"""
Generate reference fixture files from the Fortran SVMC harness.

Builds the Fortran harness, runs it, reads the JSONL file it produces,
and writes structured JSON fixture files for phydro, water, yasso, and
allocation tests.

The staged ``src/`` and ``app/`` trees under ``packages/svmc-ref`` exist so
``fpm`` can build a small, reviewable mirror of the maintained Fortran reference
sources in this repository.
Behavioral edits belong in ``vendor/SVMC/src`` and ``packages/svmc-ref/``'s
authoritative harness sources, not in the staged copies.
"""

import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
FIXTURES_DIR = HERE / "fixtures"
STAGED_SOURCES_MANIFEST = HERE / "staged-sources.json"
REPO_ROOT = HERE.parent.parent
QVIDJA_REFERENCE = REPO_ROOT / "website" / "public" / "qvidja-v1-reference.json"
INTEGRATION_FORCING_DECL_INC = HERE / "app" / "integration_forcing_decl.inc"
INTEGRATION_FORCING_DATA_INC = HERE / "app" / "integration_forcing_data.inc"

# Integration forcing: first 35 days covers the first harvest event (day 33)
INTEGRATION_NDAYS = 35
INTEGRATION_NHOURS = INTEGRATION_NDAYS * 24


def load_staged_sources_manifest() -> list[dict[str, str]]:
    """Load and validate the machine-readable staging manifest."""
    try:
        manifest = json.loads(STAGED_SOURCES_MANIFEST.read_text())
    except FileNotFoundError:
        print(f"ERROR: missing staging manifest {STAGED_SOURCES_MANIFEST}")
        sys.exit(1)
    except json.JSONDecodeError as exc:
        print(f"ERROR: bad staging manifest JSON: {exc}")
        sys.exit(1)

    entries = manifest.get("entries")
    if not isinstance(entries, list) or not entries:
        print("ERROR: staging manifest must contain a non-empty 'entries' array")
        sys.exit(1)

    seen_targets: set[str] = set()
    validated_entries: list[dict[str, str]] = []
    for index, entry in enumerate(entries, 1):
        if not isinstance(entry, dict):
            print(f"ERROR: manifest entry {index} is not an object")
            sys.exit(1)

        source = entry.get("source")
        target = entry.get("target")
        if not isinstance(source, str) or not isinstance(target, str):
            print(f"ERROR: manifest entry {index} must define string 'source' and 'target'")
            sys.exit(1)

        if target in seen_targets:
            print(f"ERROR: duplicate staged target '{target}' in manifest")
            sys.exit(1)
        seen_targets.add(target)

        target_path = Path(target)
        if target_path.parts[0] not in {"src", "app"}:
            print(f"ERROR: staged target '{target}' must live under src/ or app/")
            sys.exit(1)

        source_path = HERE.parent.parent / source
        if not source_path.exists():
            print(f"ERROR: staged source '{source}' does not exist")
            sys.exit(1)

        validated_entries.append(entry)

    return validated_entries


def generate_integration_forcing() -> None:
    """Extract a forcing slice from the Qvidja reference and write a Fortran include file."""
    print("Generating integration forcing include file …")
    if not QVIDJA_REFERENCE.exists():
        print(f"ERROR: missing Qvidja reference {QVIDJA_REFERENCE}")
        sys.exit(1)

    with open(QVIDJA_REFERENCE) as f:
        ref = json.load(f)

    hourly = ref["hourly"]
    daily = ref["daily"]

    if len(hourly["temp_hr"]) < INTEGRATION_NHOURS:
        print(f"ERROR: need {INTEGRATION_NHOURS} hourly steps, got {len(hourly['temp_hr'])}")
        sys.exit(1)
    if len(daily["dates"]) < INTEGRATION_NDAYS:
        print(f"ERROR: need {INTEGRATION_NDAYS} daily steps, got {len(daily['dates'])}")
        sys.exit(1)

    def fortran_array_decl(name: str, n: int) -> str:
        return f"  real(8) :: {name}({n})"

    def fortran_array_data(name: str, values: list) -> list[str]:
        """Generate Fortran DATA statements for a real(8) array."""
        lines = []
        chunk = 4
        for i in range(0, len(values), chunk):
            batch = values[i : i + chunk]
            vals = ", ".join(f"{v:.15e}" for v in batch)
            lines.append(f"  data {name}({i+1}:{i+len(batch)}) / {vals} /")
        return lines

    def fortran_int_array_decl(name: str, n: int) -> str:
        return f"  integer :: {name}({n})"

    def fortran_int_array_data(name: str, values: list) -> list[str]:
        vals = ", ".join(str(int(v)) for v in values)
        return [f"  data {name} / {vals} /"]

    decl: list[str] = []
    data: list[str] = []
    decl.append("  ! Auto-generated by generate.py — do not edit manually")
    decl.append(f"  ! First {INTEGRATION_NDAYS} days of Qvidja reference replay")
    decl.append(f"  integer, parameter :: INT_NDAYS = {INTEGRATION_NDAYS}")
    decl.append(f"  integer, parameter :: INT_NHOURS = {INTEGRATION_NHOURS}")
    decl.append("")
    data.append("  ! Auto-generated by generate.py — do not edit manually")
    data.append("  ! DATA statements for integration forcing arrays")
    data.append("")

    # Hourly forcing (first INTEGRATION_NHOURS values)
    for key in ["temp_hr", "rg_hr", "prec_hr", "vpd_hr", "pres_hr", "co2_hr", "wind_hr"]:
        fortran_name = "int_" + key
        vals = [float(v) for v in hourly[key][:INTEGRATION_NHOURS]]
        decl.append(fortran_array_decl(fortran_name, len(vals)))
        data.extend(fortran_array_data(fortran_name, vals))
    decl.append("")
    data.append("")

    # Daily forcing (first INTEGRATION_NDAYS values)
    for key in ["lai_day", "snowdepth_day", "soilmoist_day"]:
        fortran_name = "int_" + key
        vals = [float(v) for v in daily[key][:INTEGRATION_NDAYS]]
        decl.append(fortran_array_decl(fortran_name, len(vals)))
        data.extend(fortran_array_data(fortran_name, vals))

    int_manage = daily["manage_type"][:INTEGRATION_NDAYS]
    decl.append(fortran_int_array_decl("int_manage_type", len(int_manage)))
    data.extend(fortran_int_array_data("int_manage_type", int_manage))

    for key in ["manage_c_in", "manage_c_out"]:
        fortran_name = "int_" + key
        vals = [float(v) for v in daily[key][:INTEGRATION_NDAYS]]
        decl.append(fortran_array_decl(fortran_name, len(vals)))
        data.extend(fortran_array_data(fortran_name, vals))
    decl.append("")
    data.append("")

    INTEGRATION_FORCING_DECL_INC.parent.mkdir(exist_ok=True)
    INTEGRATION_FORCING_DECL_INC.write_text("\n".join(decl) + "\n")
    INTEGRATION_FORCING_DATA_INC.write_text("\n".join(data) + "\n")
    print(f"Wrote {INTEGRATION_FORCING_DECL_INC} ({len(decl)} lines)")
    print(f"Wrote {INTEGRATION_FORCING_DATA_INC} ({len(data)} lines)")


def build_harness() -> None:
    """Build harness using fpm."""
    import shutil

    # Generate integration forcing data before building
    generate_integration_forcing()

    print("Building Fortran harness …")
    staged_entries = load_staged_sources_manifest()
    # Stage the exact subset of maintained reference sources required by the harness.
    # The vendor tree remains the in-repo numerical reference source of truth.
    for entry in staged_entries:
        source_path = HERE.parent.parent / entry["source"]
        target_path = HERE / entry["target"]
        target_path.parent.mkdir(exist_ok=True)
        shutil.copy2(source_path, target_path)
    # Get netcdf include flags (may be empty if not installed)
    import subprocess
    nf_flags = ""
    try:
        nf_flags = subprocess.run(
            ["nf-config", "--fflags"],
            capture_output=True, text=True, check=True
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass
    fpm_flags = f"-O2 -g -m64 -freal-4-real-8 -fcheck=all {nf_flags}".strip()
    result = subprocess.run(
        ["fpm", "build", "--flag", fpm_flags],
        cwd=HERE,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("=== STDOUT ===", result.stdout, sep="\n")
        print("=== STDERR ===", result.stderr, sep="\n")
        sys.exit(1)
    print("Build OK")


def run_harness() -> list[dict]:
    """Execute the harness and parse its JSONL file output."""
    print("Running harness …")
    # Get netcdf include flags
    nf_flags = ""
    try:
        nf_flags = subprocess.run(
            ["nf-config", "--fflags"],
            capture_output=True, text=True, check=True
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass
    fpm_flags = f"-O2 -g -m64 -freal-4-real-8 -fcheck=all {nf_flags}".strip()
    result = subprocess.run(
        ["fpm", "run", "--flag", fpm_flags],
        cwd=HERE,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("=== STDERR ===", result.stderr, sep="\n")
        sys.exit(1)
    if result.stdout.strip():
        print(result.stdout.strip())

    jsonl_path = HERE / "fixtures.jsonl"
    if not jsonl_path.exists():
        print(f"ERROR: harness did not produce {jsonl_path}")
        sys.exit(1)

    records: list[dict] = []
    for i, line in enumerate(jsonl_path.read_text().strip().splitlines(), 1):
        line = line.strip()
        if not line:
            continue
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError as exc:
            print(f"Bad JSON on line {i}: {exc}\n  {line!r}")
            sys.exit(1)

    print(f"Parsed {len(records)} records from {jsonl_path.name}")
    return records


PHYDRO_FUNCTIONS = {
    "ftemp_arrh",
    "gammastar",
    "ftemp_kphio_c3",
    "ftemp_kphio_c4",
    "density_h2o",
    "viscosity_h2o",
    "calc_kmm",
    "scale_conductivity",
    "calc_gs",
    "calc_assim_light_limited",
    "fn_profit",
    "quadratic",
    "pmodel_hydraulics_numerical",
}

WATER_FUNCTIONS = {
    "e_sat",
    "penman_monteith",
    "soil_water_retention_curve",
    "soil_hydraulic_conductivity",
    "aerodynamics",
    "exponential_smooth_met",
    "canopy_water_snow",
    "ground_evaporation",
    "canopy_water_flux",
    "soil_water",
}

YASSO_FUNCTIONS = {
    "inputs_to_fractions",
    "matrixnorm",
    "matrixexp",
    "mod5c20",
    "decompose",
    "initialize_totc",
}

ALLOCATION_FUNCTIONS = {
    "alloc_hypothesis_2",
    "invert_alloc",
}

INTEGRATION_FUNCTIONS = {
    "integration_daily",
}


def split_and_write(records: list[dict]) -> None:
    """Split records into phydro/water and write JSON fixture files."""
    FIXTURES_DIR.mkdir(exist_ok=True)

    phydro: dict[str, list] = defaultdict(list)
    water: dict[str, list] = defaultdict(list)
    yasso: dict[str, list] = defaultdict(list)
    alloc: dict[str, list] = defaultdict(list)
    integration: dict[str, list] = defaultdict(list)

    for rec in records:
        fn = rec["fn"]
        if fn in PHYDRO_FUNCTIONS:
            phydro[fn].append({"inputs": rec["inputs"], "output": rec["output"]})
        elif fn in WATER_FUNCTIONS:
            water[fn].append({"inputs": rec["inputs"], "output": rec["output"]})
        elif fn in YASSO_FUNCTIONS:
            yasso[fn].append({"inputs": rec["inputs"], "output": rec["output"]})
        elif fn in ALLOCATION_FUNCTIONS:
            alloc[fn].append({"inputs": rec["inputs"], "output": rec["output"]})
        elif fn in INTEGRATION_FUNCTIONS:
            integration[fn].append({"inputs": rec["inputs"], "output": rec["output"]})
        else:
            print(f"WARNING: unknown function '{fn}', skipping")

    phydro_path = FIXTURES_DIR / "phydro.json"
    water_path = FIXTURES_DIR / "water.json"
    yasso_path = FIXTURES_DIR / "yasso.json"
    alloc_path = FIXTURES_DIR / "allocation.json"
    integration_path = FIXTURES_DIR / "integration.json"

    phydro_path.write_text(json.dumps(dict(phydro), indent=2) + "\n")
    water_path.write_text(json.dumps(dict(water), indent=2) + "\n")
    yasso_path.write_text(json.dumps(dict(yasso), indent=2) + "\n")
    alloc_path.write_text(json.dumps(dict(alloc), indent=2) + "\n")
    integration_path.write_text(json.dumps(dict(integration), indent=2) + "\n")

    print(f"Wrote {phydro_path}  ({sum(len(v) for v in phydro.values())} cases)")
    print(f"Wrote {water_path}  ({sum(len(v) for v in water.values())} cases)")
    print(f"Wrote {yasso_path}  ({sum(len(v) for v in yasso.values())} cases)")
    print(f"Wrote {alloc_path}  ({sum(len(v) for v in alloc.values())} cases)")
    print(f"Wrote {integration_path}  ({sum(len(v) for v in integration.values())} cases)")


def main() -> None:
    build_harness()
    records = run_harness()
    split_and_write(records)
    print("Done.")


if __name__ == "__main__":
    main()
